package com.entity;
// Generated 2016-10-26 11:09:08 by Hibernate Tools 4.3.1



/**
 * Cart generated by hbm2java
 */
public class Cart  implements java.io.Serializable {


     private Integer cid;
     private Buyer buyer;
     private Merchandise merchandise;
     private int quantity;
     private float total;

    public Cart() {
    }

    public Cart(Buyer buyer, Merchandise merchandise, int quantity, float total) {
       this.buyer = buyer;
       this.merchandise = merchandise;
       this.quantity = quantity;
       this.total = total;
    }
   
    public Integer getCid() {
        return this.cid;
    }
    
    public void setCid(Integer cid) {
        this.cid = cid;
    }
    public Buyer getBuyer() {
        return this.buyer;
    }
    
    public void setBuyer(Buyer buyer) {
        this.buyer = buyer;
    }
    public Merchandise getMerchandise() {
        return this.merchandise;
    }
    
    public void setMerchandise(Merchandise merchandise) {
        this.merchandise = merchandise;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public float getTotal() {
        return this.total;
    }
    
    public void setTotal(float total) {
        this.total = total;
    }




}


