package com.entity;
// Generated 2016-10-26 11:09:08 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Delivery generated by hbm2java
 */
public class Delivery  implements java.io.Serializable {


     private Integer deliveid;
     private String deliveinfo;
     private Date senddate;
     private Date arrdate;
     private float money;
     private Set orders = new HashSet(0);

    public Delivery() {
    }

	
    public Delivery(String deliveinfo, Date senddate, float money) {
        this.deliveinfo = deliveinfo;
        this.senddate = senddate;
        this.money = money;
    }
    public Delivery(String deliveinfo, Date senddate, Date arrdate, float money, Set orders) {
       this.deliveinfo = deliveinfo;
       this.senddate = senddate;
       this.arrdate = arrdate;
       this.money = money;
       this.orders = orders;
    }
   
    public Integer getDeliveid() {
        return this.deliveid;
    }
    
    public void setDeliveid(Integer deliveid) {
        this.deliveid = deliveid;
    }
    public String getDeliveinfo() {
        return this.deliveinfo;
    }
    
    public void setDeliveinfo(String deliveinfo) {
        this.deliveinfo = deliveinfo;
    }
    public Date getSenddate() {
        return this.senddate;
    }
    
    public void setSenddate(Date senddate) {
        this.senddate = senddate;
    }
    public Date getArrdate() {
        return this.arrdate;
    }
    
    public void setArrdate(Date arrdate) {
        this.arrdate = arrdate;
    }
    public float getMoney() {
        return this.money;
    }
    
    public void setMoney(float money) {
        this.money = money;
    }
    public Set getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set orders) {
        this.orders = orders;
    }




}


