package com.entity;
// Generated 2016-10-26 11:09:08 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Inoutcome generated by hbm2java
 */
public class Inoutcome  implements java.io.Serializable {


     private Integer ioid;
     private float money;
     private String des;
     private Date date;
     private boolean isinout;

    public Inoutcome() {
    }

    public Inoutcome(float money, String des, Date date, boolean isinout) {
       this.money = money;
       this.des = des;
       this.date = date;
       this.isinout = isinout;
    }
   
    public Integer getIoid() {
        return this.ioid;
    }
    
    public void setIoid(Integer ioid) {
        this.ioid = ioid;
    }
    public float getMoney() {
        return this.money;
    }
    
    public void setMoney(float money) {
        this.money = money;
    }
    public String getDes() {
        return this.des;
    }
    
    public void setDes(String des) {
        this.des = des;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public boolean isIsinout() {
        return this.isinout;
    }
    
    public void setIsinout(boolean isinout) {
        this.isinout = isinout;
    }




}


