package com.entity;
// Generated 2016-10-26 11:09:08 by Hibernate Tools 4.3.1



/**
 * Manager generated by hbm2java
 */
public class Manager  implements java.io.Serializable {


     private Integer managid;
     private String username;
     private String password;

    public Manager() {
    }

    public Manager(String username, String password) {
       this.username = username;
       this.password = password;
    }
   
    public Integer getManagid() {
        return this.managid;
    }
    
    public void setManagid(Integer managid) {
        this.managid = managid;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


