package com.entity;
// Generated 2016-10-26 11:09:08 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Merpic generated by hbm2java
 */
public class Merpic  implements java.io.Serializable {


     private Integer pid;
     private byte[] p0;
     private byte[] p1;
     private byte[] p2;
     private byte[] p3;
     private byte[] p4;
     private byte[] p5;
     private byte[] p6;
     private byte[] p7;
     private byte[] p8;
     private Set merchandises = new HashSet(0);

    public Merpic() {
    }

    public Merpic(byte[] p0, byte[] p1, byte[] p2, byte[] p3, byte[] p4, byte[] p5, byte[] p6, byte[] p7, byte[] p8, Set merchandises) {
       this.p0 = p0;
       this.p1 = p1;
       this.p2 = p2;
       this.p3 = p3;
       this.p4 = p4;
       this.p5 = p5;
       this.p6 = p6;
       this.p7 = p7;
       this.p8 = p8;
       this.merchandises = merchandises;
    }
   
    public Integer getPid() {
        return this.pid;
    }
    
    public void setPid(Integer pid) {
        this.pid = pid;
    }
    public byte[] getP0() {
        return this.p0;
    }
    
    public void setP0(byte[] p0) {
        this.p0 = p0;
    }
    public byte[] getP1() {
        return this.p1;
    }
    
    public void setP1(byte[] p1) {
        this.p1 = p1;
    }
    public byte[] getP2() {
        return this.p2;
    }
    
    public void setP2(byte[] p2) {
        this.p2 = p2;
    }
    public byte[] getP3() {
        return this.p3;
    }
    
    public void setP3(byte[] p3) {
        this.p3 = p3;
    }
    public byte[] getP4() {
        return this.p4;
    }
    
    public void setP4(byte[] p4) {
        this.p4 = p4;
    }
    public byte[] getP5() {
        return this.p5;
    }
    
    public void setP5(byte[] p5) {
        this.p5 = p5;
    }
    public byte[] getP6() {
        return this.p6;
    }
    
    public void setP6(byte[] p6) {
        this.p6 = p6;
    }
    public byte[] getP7() {
        return this.p7;
    }
    
    public void setP7(byte[] p7) {
        this.p7 = p7;
    }
    public byte[] getP8() {
        return this.p8;
    }
    
    public void setP8(byte[] p8) {
        this.p8 = p8;
    }
    public Set getMerchandises() {
        return this.merchandises;
    }
    
    public void setMerchandises(Set merchandises) {
        this.merchandises = merchandises;
    }




}


