package com.entity;
// Generated 2016-10-26 11:09:08 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Order generated by hbm2java
 */
public class Order  implements java.io.Serializable {


     private Integer oid;
     private Buyer buyer;
     private Delivery delivery;
     private Merchandise merchandise;
     private int quantity;
     private float total;
     private float odiscount;
     private boolean ispay;
     private boolean isarrive;
     private Date startdate;
     private Date enddate;

    public Order() {
    }

	
    public Order(Buyer buyer, Delivery delivery, Merchandise merchandise, int quantity, float total, float odiscount, boolean ispay, boolean isarrive, Date startdate) {
        this.buyer = buyer;
        this.delivery = delivery;
        this.merchandise = merchandise;
        this.quantity = quantity;
        this.total = total;
        this.odiscount = odiscount;
        this.ispay = ispay;
        this.isarrive = isarrive;
        this.startdate = startdate;
    }
    public Order(Buyer buyer, Delivery delivery, Merchandise merchandise, int quantity, float total, float odiscount, boolean ispay, boolean isarrive, Date startdate, Date enddate) {
       this.buyer = buyer;
       this.delivery = delivery;
       this.merchandise = merchandise;
       this.quantity = quantity;
       this.total = total;
       this.odiscount = odiscount;
       this.ispay = ispay;
       this.isarrive = isarrive;
       this.startdate = startdate;
       this.enddate = enddate;
    }
   
    public Integer getOid() {
        return this.oid;
    }
    
    public void setOid(Integer oid) {
        this.oid = oid;
    }
    public Buyer getBuyer() {
        return this.buyer;
    }
    
    public void setBuyer(Buyer buyer) {
        this.buyer = buyer;
    }
    public Delivery getDelivery() {
        return this.delivery;
    }
    
    public void setDelivery(Delivery delivery) {
        this.delivery = delivery;
    }
    public Merchandise getMerchandise() {
        return this.merchandise;
    }
    
    public void setMerchandise(Merchandise merchandise) {
        this.merchandise = merchandise;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public float getTotal() {
        return this.total;
    }
    
    public void setTotal(float total) {
        this.total = total;
    }
    public float getOdiscount() {
        return this.odiscount;
    }
    
    public void setOdiscount(float odiscount) {
        this.odiscount = odiscount;
    }
    public boolean isIspay() {
        return this.ispay;
    }
    
    public void setIspay(boolean ispay) {
        this.ispay = ispay;
    }
    public boolean isIsarrive() {
        return this.isarrive;
    }
    
    public void setIsarrive(boolean isarrive) {
        this.isarrive = isarrive;
    }
    public Date getStartdate() {
        return this.startdate;
    }
    
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }
    public Date getEnddate() {
        return this.enddate;
    }
    
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }




}


