package com.entity;
// Generated 2016-10-26 11:09:08 by Hibernate Tools 4.3.1



/**
 * Recommendation generated by hbm2java
 */
public class Recommendation  implements java.io.Serializable {


     private Integer recomid;
     private Merchandise merchandise;
     private Integer recomrate;
     private String recominfo;

    public Recommendation() {
    }

	
    public Recommendation(Merchandise merchandise) {
        this.merchandise = merchandise;
    }
    public Recommendation(Merchandise merchandise, Integer recomrate, String recominfo) {
       this.merchandise = merchandise;
       this.recomrate = recomrate;
       this.recominfo = recominfo;
    }
   
    public Integer getRecomid() {
        return this.recomid;
    }
    
    public void setRecomid(Integer recomid) {
        this.recomid = recomid;
    }
    public Merchandise getMerchandise() {
        return this.merchandise;
    }
    
    public void setMerchandise(Merchandise merchandise) {
        this.merchandise = merchandise;
    }
    public Integer getRecomrate() {
        return this.recomrate;
    }
    
    public void setRecomrate(Integer recomrate) {
        this.recomrate = recomrate;
    }
    public String getRecominfo() {
        return this.recominfo;
    }
    
    public void setRecominfo(String recominfo) {
        this.recominfo = recominfo;
    }




}


