package com.entity;
// Generated 2016-10-26 11:09:08 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Saler generated by hbm2java
 */
public class Saler  implements java.io.Serializable {


     private Integer sid;
     private String name;
     private String phone;
     private String address;
     private String username;
     private String passwrod;
     private String idcardnum;
     private Set merchandises = new HashSet(0);

    public Saler() {
    }

	
    public Saler(String name, String phone, String username, String passwrod, String idcardnum) {
        this.name = name;
        this.phone = phone;
        this.username = username;
        this.passwrod = passwrod;
        this.idcardnum = idcardnum;
    }
    public Saler(String name, String phone, String address, String username, String passwrod, String idcardnum, Set merchandises) {
       this.name = name;
       this.phone = phone;
       this.address = address;
       this.username = username;
       this.passwrod = passwrod;
       this.idcardnum = idcardnum;
       this.merchandises = merchandises;
    }
   
    public Integer getSid() {
        return this.sid;
    }
    
    public void setSid(Integer sid) {
        this.sid = sid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPasswrod() {
        return this.passwrod;
    }
    
    public void setPasswrod(String passwrod) {
        this.passwrod = passwrod;
    }
    public String getIdcardnum() {
        return this.idcardnum;
    }
    
    public void setIdcardnum(String idcardnum) {
        this.idcardnum = idcardnum;
    }
    public Set getMerchandises() {
        return this.merchandises;
    }
    
    public void setMerchandises(Set merchandises) {
        this.merchandises = merchandises;
    }




}


